### ISSUE TITLE
Pre-launch checklist - absolutely necessary

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#28]
@hupili @frankinit @Kateliuxue 
Please check and add items.
- Homepage
  - [ ] URL is right: initiumlab.com
  - [ ] webpage tab title is correct: Initium Lab
  - [ ] Text is displayed correctly
  - [ ] No obvious spelling and grammatical mistakes
  - [ ] Images are displayed correctly
  - [ ] Email subscription works
  - [ ] All links are clickable and point to expected destinations

- About page
  - [ ] URL is correct: initiumlab.com/about
  - [ ] webpage tab title is correct: Initium Lab
  - [ ] Information about Initium Lab is correct
  - [ ] Information about the team is correct (may need to check with each team members)
  - [ ] Information about credits is correct
  - [ ] No obvious spelling and grammatical mistakes
  - [ ] The email address for contacting us is displayed correctly
  - [ ] The email address for contacting us leads to the correct destination
  - [ ] We do receive emails sent to the contact email address

- Blog sub-homepage
  - [ ] URL is correct: initiumlab.com/blog
  - [ ] webpage tab is correct: Initium Lab
  - [ ] Blog title is correct and clickable, which leads to the correct blog page
  - [ ] The text is displayed correctly
  - [ ] The image is displayed correctly
  - [ ] The "Read more" button is clickable and leads to the correct blog page

- Sidebar (not available on homepage)
  - [ ] Sidebar button can activate sidebar on about page, which does *not* push main contents aside
  - [ ] Sidebar button can activate sidebar on blog homepage, which does *not* push main contents aside
  - [ ] Sidebar button can activate sidebar on blog post pages, which does *not* push main contents aside
  - [ ] Search works as expected (exercise common sense)
  - [ ] Tags under search are clickable and lead to expected destinations
  - [ ] "ToTop" button (the triangle at the bottom right) takes the page to the top

- Tag view (such as http://initiumlab.com/tags/Accessibility/)
  - [ ] The text is displayed correctly
  - [ ] All posts with the selected tag is shown
  - [ ] No post without the select tag is shown

- HTTPS:// accessability
  - [ ] able to access through https://initiumlab.com

**Comment by frankinit** [comment]
Noted with thanks.

**Comment by Kateliuxue** [comment]
OK, thanks.
