### ISSUE TITLE
Tracking user actions

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#64]
e.g. lightbox is not tracked by GA by default. 

TODO:

* [x] Track lightbox behaviour
* [x] Track RSS click
* [x] Track sidebar usage 
* [x] Track search usage
* [x] Track TOC usage
* ...

We can determine which elements to add/ to remove based on this data.

**Comment by andyshuxin** [comment]
Added customised event tracking for open and close of lightboxes, with https://github.com/initiumlab/hexo-theme-next/commit/2ff4279afdad86b1bd86dccfe67168073f1baa7a
Will need to check Google Analytics to ensure it actually works before added event tracking for other functionalities.

**Comment by hupili** [comment]
Need to review the effect next week and make sure GA tracking is working. After that, we can also create segmented experiments using GA. This saves a lot backend maintenance work.

**Comment by andyshuxin** [comment]
Implemented with https://github.com/initiumlab/hexo-theme-next/commit/49c8d1980aee96e97f54f79b38826f77fb3d840c, except search tracking.

The Swifttype search engine provide their own analytics.
